name: Create posts

on:
  push:
    branches:
      - main

jobs:
  create-posts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi
    - name: Create paper posts
      run: |
        pwd
        mkdir posts
        python scripts/createPaperPosts.py
    - name: Archive posts
      uses: actions/upload-artifact@v4
      with:
        name: posts-artifact
        path: posts/
  deploy-posts:
    runs-on: ubuntu-latest
    needs: create-posts
    permissions:
      contents: write
      pages: write
    steps:
    - name: Checkout GitHub Pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    - name: Copy posts
      uses: actions/download-artifact@v4
      with:
        name: posts-artifact
        path: docs/_posts
    - name: Check for changes
      id: changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email {user.id}+{user.login}@users.noreply.github.com
        git diff --quiet || echo "changes_detected"
    - name: Commit and push changes
      if: success() && steps.changes.outputs.changes_detected == 'true'
      run: |
        git add docs/_posts/*
        git commit -m "Add new files to gh-pages"
        git push origin gh-pages
    